--Q1. What is the total revenue generated by the male vs. female customers?
select gender, SUM(purchase_amount) as 'revenue'
from customer
group by gender

--Q2. Which customers use a discount but still they spend more the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS FLOAT)) DESC;

--Q4. Compare the average Purchase amounts between standard and xpress shipping
select shipping_type, round(AVG(purchase_amount),2) 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_spend, total_revenue desc

--Q6. Which 5 products have the highest percentage of puchases with discount applied?
select top 5 item_purchased,
ROUND(100*SUM(case when discount_applied='Yes' then 1 else 0 end)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc

--Q7. Segment customers into New, Returning and loyal bsed on their total number of previous purchases,and show the count of each segement
with customer_type as (
select customer_id, previous_purchases,
CASE 
 WHEN previous_purchases=1 Then 'New'
 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
 Else 'Loyal'
 End as customer_segment
from customer
)

select customer_segment, COUNT(*) as number_of_customers
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within eacch category?
with item_counts as (
select category, item_purchased,
COUNT(customer_id) as total_customers,
ROW_NUMBER() over (partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category, item_purchased
)

SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


